/*
Toae ThreatMapper

Toae Runtime API provides programmatic control over Toae microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: toaedev@toaesecurity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance{}

// ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance struct for ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance
type ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance struct {
	New []ModelCloudCompliance `json:"new"`
}

type _ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance

// NewModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance instantiates a new ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance(new []ModelCloudCompliance) *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance {
	this := ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance{}
	this.New = new
	return &this
}

// NewModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudComplianceWithDefaults instantiates a new ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudComplianceWithDefaults() *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance {
	this := ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance{}
	return &this
}

// GetNew returns the New field value
// If the value is explicit nil, the zero value for []ModelCloudCompliance will be returned
func (o *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) GetNew() []ModelCloudCompliance {
	if o == nil {
		var ret []ModelCloudCompliance
		return ret
	}

	return o.New
}

// GetNewOk returns a tuple with the New field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) GetNewOk() ([]ModelCloudCompliance, bool) {
	if o == nil || IsNil(o.New) {
		return nil, false
	}
	return o.New, true
}

// SetNew sets field value
func (o *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) SetNew(v []ModelCloudCompliance) {
	o.New = v
}

func (o ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.New != nil {
		toSerialize["new"] = o.New
	}
	return toSerialize, nil
}

func (o *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"new",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance := _ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance{}

	err = json.Unmarshal(bytes, &varModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance)

	if err != nil {
		return err
	}

	*o = ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance(varModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance)

	return err
}

type NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance struct {
	value *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance
	isSet bool
}

func (v NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) Get() *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance {
	return v.value
}

func (v *NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) Set(val *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) {
	v.value = val
	v.isSet = true
}

func (v NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) IsSet() bool {
	return v.isSet
}

func (v *NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance(val *ModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) *NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance {
	return &NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance{value: val, isSet: true}
}

func (v NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelScanCompareResGithubComToaeThreatMapperToaeServerModelCloudCompliance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


